# Generated by Django 4.2.2 on 2023-07-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=39)),
                ('user_agent', models.CharField(max_length=100)),
                ('redirect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quicklink.redirect')),
            ],
        ),
    ]
