# Generated by Django 4.2.2 on 2023-07-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='user_agent',
            field=models.TextField(),
        ),
    ]
